--------------- accounts START ----------------
-- DROP TABLE IF EXIST
DROP TABLE IF EXISTS accounts CASCADE;

-- CREATE TABLE
CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_name TEXT NOT NULL,
    balance NUMERIC(19,4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0
);

-- COMMENT
COMMENT ON TABLE accounts IS 'Account master data';
COMMENT ON COLUMN accounts.id IS 'PK: surrogate identifier for account';
COMMENT ON COLUMN accounts.owner_name IS 'Account owner name';
COMMENT ON COLUMN accounts.balance IS 'Current account balance';
COMMENT ON COLUMN accounts.currency IS 'ISO 4217 currency code';
COMMENT ON COLUMN accounts.created_at IS 'Audit: creation timestamp in UTC';
COMMENT ON COLUMN accounts.version IS 'Optimistic locking version';

-- CONSTRAINT
ALTER TABLE accounts
    ADD CONSTRAINT accounts_pk PRIMARY KEY (id);
ALTER TABLE accounts
    ADD CONSTRAINT accounts_balance_non_negative_ck CHECK (balance >= 0);
ALTER TABLE accounts
    ADD CONSTRAINT accounts_currency_len_ck CHECK (char_length(currency) = 3);

-- CREATE INDEX
-- (none, PK covers identity lookups)

-- TRIGGER
-- (none)
--------------- accounts END ----------------

--------------- transactions START ----------------
-- DROP TABLE IF EXIST
DROP TABLE IF EXISTS transactions CASCADE;

-- CREATE TABLE
CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sender_account_id BIGINT NOT NULL,
    receiver_account_id BIGINT NOT NULL,
    amount NUMERIC(19,4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(16) NOT NULL,
    idempotency_key TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    failure_reason TEXT
);

-- COMMENT
COMMENT ON TABLE transactions IS 'Payment transaction records';
COMMENT ON COLUMN transactions.id IS 'PK: surrogate identifier for transaction';
COMMENT ON COLUMN transactions.sender_account_id IS 'FK to sender account';
COMMENT ON COLUMN transactions.receiver_account_id IS 'FK to receiver account';
COMMENT ON COLUMN transactions.amount IS 'Transferred amount';
COMMENT ON COLUMN transactions.currency IS 'ISO 4217 currency code';
COMMENT ON COLUMN transactions.status IS 'Transaction status (PENDING/COMPLETED/FAILED)';
COMMENT ON COLUMN transactions.idempotency_key IS 'Unique idempotency key for deduplication';
COMMENT ON COLUMN transactions.created_at IS 'Audit: creation timestamp in UTC';
COMMENT ON COLUMN transactions.updated_at IS 'Audit: last update timestamp in UTC';
COMMENT ON COLUMN transactions.failure_reason IS 'Optional failure reason when status is FAILED';

-- CONSTRAINT
ALTER TABLE transactions
    ADD CONSTRAINT transactions_pk PRIMARY KEY (id);
ALTER TABLE transactions
    ADD CONSTRAINT transactions_sender_account_fk FOREIGN KEY (sender_account_id)
        REFERENCES accounts (id);
ALTER TABLE transactions
    ADD CONSTRAINT transactions_receiver_account_fk FOREIGN KEY (receiver_account_id)
        REFERENCES accounts (id);
ALTER TABLE transactions
    ADD CONSTRAINT transactions_amount_positive_ck CHECK (amount > 0);
ALTER TABLE transactions
    ADD CONSTRAINT transactions_currency_len_ck CHECK (char_length(currency) = 3);
ALTER TABLE transactions
    ADD CONSTRAINT transactions_status_ck CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED'));
ALTER TABLE transactions
    ADD CONSTRAINT transactions_idempotency_key_uk UNIQUE (idempotency_key);

-- CREATE INDEX
CREATE INDEX transactions_sender_account_idx ON transactions (sender_account_id);
CREATE INDEX transactions_receiver_account_idx ON transactions (receiver_account_id);
CREATE INDEX transactions_status_idx ON transactions (status);

-- TRIGGER
CREATE OR REPLACE FUNCTION update_utc_function()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER transactions_update_utc_trigger
BEFORE UPDATE
ON transactions
FOR EACH ROW
EXECUTE PROCEDURE update_utc_function();
--------------- transactions END ----------------

--------------- notification_outbox START ----------------
-- DROP TABLE IF EXIST
DROP TABLE IF EXISTS notification_outbox CASCADE;

-- CREATE TABLE
CREATE TABLE notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id BIGINT NOT NULL,
    status VARCHAR(16) NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at TIMESTAMPTZ,
    retry_count INTEGER NOT NULL DEFAULT 0
);

-- COMMENT
COMMENT ON TABLE notification_outbox IS 'Outbox records for notification delivery';
COMMENT ON COLUMN notification_outbox.id IS 'PK: surrogate identifier for outbox message';
COMMENT ON COLUMN notification_outbox.transaction_id IS 'FK to transaction';
COMMENT ON COLUMN notification_outbox.status IS 'Outbox status (PENDING/PROCESSING/SENT/FAILED)';
COMMENT ON COLUMN notification_outbox.payload IS 'Serialized notification payload';
COMMENT ON COLUMN notification_outbox.created_at IS 'Audit: creation timestamp in UTC';
COMMENT ON COLUMN notification_outbox.sent_at IS 'Timestamp when notification was sent';
COMMENT ON COLUMN notification_outbox.retry_count IS 'Number of delivery retry attempts';

-- CONSTRAINT
ALTER TABLE notification_outbox
    ADD CONSTRAINT notification_outbox_pk PRIMARY KEY (id);
ALTER TABLE notification_outbox
    ADD CONSTRAINT notification_outbox_transaction_fk FOREIGN KEY (transaction_id)
        REFERENCES transactions (id);
ALTER TABLE notification_outbox
    ADD CONSTRAINT notification_outbox_status_ck CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED'));
ALTER TABLE notification_outbox
    ADD CONSTRAINT notification_outbox_retry_count_ck CHECK (retry_count >= 0);

-- CREATE INDEX
CREATE INDEX notification_outbox_status_idx ON notification_outbox (status);
CREATE INDEX notification_outbox_transaction_idx ON notification_outbox (transaction_id);

-- TRIGGER
-- (none)
--------------- notification_outbox END ----------------